#Set Parameters
kP : 3
kA : 8
kB : -1.5
max_linear_speed : 1E9
min_linear_speed : 0
max_angular_speed : 1E9
min_angular_speed : 0
max_linear_acceleration : 1E9
max_angular_acceleration : 1E9
linear_tolerance : 0.1 # 2.5cm
angular_tolerance : 3/180*pi # 3 degrees
forward_movement_only : False