---
#PID Gain values for translation
kP : 3
kI : 0
kD : 0
#PID Gain values for rotation
kP_r : 2
kI_r : 0
kD_r : 0
#Max/Min values of speeds
max_linear_speed : 0.20
min_linear_speed : 0.0001
max_angular_speed : 0.1
min_angular_speed : 0.0001
#Permissible errors for linear and angular motion 
linear_tolerance : 0.1 
angular_tolerance : 0.053   #3/180*pi